on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

env:
  CI_BUILD: true

jobs:
  build:
    runs-on: apexstudios
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Mark Gradle as Executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build